"""Country calling codes for the phone field in the registration form.

Names are in Spanish and the list is already sorted alphabetically by name,
so templates can render it as-is without sorting at request time.
"""

# (ISO 3166-1 alpha-2, Spanish name, E.164 calling code)
COUNTRIES: list[tuple[str, str, str]] = [
    ("AF", "Afganistán", "+93"),
    ("AL", "Albania", "+355"),
    ("DE", "Alemania", "+49"),
    ("AD", "Andorra", "+376"),
    ("AO", "Angola", "+244"),
    ("SA", "Arabia Saudí", "+966"),
    ("DZ", "Argelia", "+213"),
    ("AR", "Argentina", "+54"),
    ("AM", "Armenia", "+374"),
    ("AU", "Australia", "+61"),
    ("AT", "Austria", "+43"),
    ("AZ", "Azerbaiyán", "+994"),
    ("BE", "Bélgica", "+32"),
    ("BZ", "Belice", "+501"),
    ("BJ", "Benín", "+229"),
    ("BY", "Bielorrusia", "+375"),
    ("BO", "Bolivia", "+591"),
    ("BA", "Bosnia y Herzegovina", "+387"),
    ("BW", "Botsuana", "+267"),
    ("BR", "Brasil", "+55"),
    ("BG", "Bulgaria", "+359"),
    ("BF", "Burkina Faso", "+226"),
    ("BI", "Burundi", "+257"),
    ("BT", "Bután", "+975"),
    ("CV", "Cabo Verde", "+238"),
    ("KH", "Camboya", "+855"),
    ("CM", "Camerún", "+237"),
    ("CA", "Canadá", "+1"),
    ("QA", "Catar", "+974"),
    ("TD", "Chad", "+235"),
    ("CZ", "Chequia", "+420"),
    ("CL", "Chile", "+56"),
    ("CN", "China", "+86"),
    ("CY", "Chipre", "+357"),
    ("CO", "Colombia", "+57"),
    ("KM", "Comoras", "+269"),
    ("KP", "Corea del Norte", "+850"),
    ("KR", "Corea del Sur", "+82"),
    ("CI", "Costa de Marfil", "+225"),
    ("CR", "Costa Rica", "+506"),
    ("HR", "Croacia", "+385"),
    ("CU", "Cuba", "+53"),
    ("DK", "Dinamarca", "+45"),
    ("DJ", "Yibuti", "+253"),
    ("DO", "República Dominicana", "+1"),
    ("EC", "Ecuador", "+593"),
    ("EG", "Egipto", "+20"),
    ("SV", "El Salvador", "+503"),
    ("AE", "Emiratos Árabes Unidos", "+971"),
    ("ER", "Eritrea", "+291"),
    ("SK", "Eslovaquia", "+421"),
    ("SI", "Eslovenia", "+386"),
    ("ES", "España", "+34"),
    ("US", "Estados Unidos", "+1"),
    ("EE", "Estonia", "+372"),
    ("ET", "Etiopía", "+251"),
    ("PH", "Filipinas", "+63"),
    ("FI", "Finlandia", "+358"),
    ("FJ", "Fiyi", "+679"),
    ("FR", "Francia", "+33"),
    ("GA", "Gabón", "+241"),
    ("GM", "Gambia", "+220"),
    ("GE", "Georgia", "+995"),
    ("GH", "Ghana", "+233"),
    ("GI", "Gibraltar", "+350"),
    ("GR", "Grecia", "+30"),
    ("GD", "Granada", "+1"),
    ("GT", "Guatemala", "+502"),
    ("GY", "Guyana", "+592"),
    ("GN", "Guinea", "+224"),
    ("GQ", "Guinea Ecuatorial", "+240"),
    ("GW", "Guinea-Bisáu", "+245"),
    ("HT", "Haití", "+509"),
    ("HN", "Honduras", "+504"),
    ("HU", "Hungría", "+36"),
    ("IN", "India", "+91"),
    ("ID", "Indonesia", "+62"),
    ("IQ", "Irak", "+964"),
    ("IR", "Irán", "+98"),
    ("IE", "Irlanda", "+353"),
    ("IS", "Islandia", "+354"),
    ("IL", "Israel", "+972"),
    ("IT", "Italia", "+39"),
    ("JM", "Jamaica", "+1"),
    ("JP", "Japón", "+81"),
    ("JO", "Jordania", "+962"),
    ("KZ", "Kazajistán", "+7"),
    ("KE", "Kenia", "+254"),
    ("KG", "Kirguistán", "+996"),
    ("KI", "Kiribati", "+686"),
    ("KW", "Kuwait", "+965"),
    ("LA", "Laos", "+856"),
    ("LS", "Lesoto", "+266"),
    ("LV", "Letonia", "+371"),
    ("LB", "Líbano", "+961"),
    ("LR", "Liberia", "+231"),
    ("LY", "Libia", "+218"),
    ("LI", "Liechtenstein", "+423"),
    ("LT", "Lituania", "+370"),
    ("LU", "Luxemburgo", "+352"),
    ("MK", "Macedonia del Norte", "+389"),
    ("MG", "Madagascar", "+261"),
    ("MY", "Malasia", "+60"),
    ("MW", "Malaui", "+265"),
    ("MV", "Maldivas", "+960"),
    ("ML", "Malí", "+223"),
    ("MT", "Malta", "+356"),
    ("MA", "Marruecos", "+212"),
    ("MU", "Mauricio", "+230"),
    ("MR", "Mauritania", "+222"),
    ("MX", "México", "+52"),
    ("MD", "Moldavia", "+373"),
    ("MC", "Mónaco", "+377"),
    ("MN", "Mongolia", "+976"),
    ("ME", "Montenegro", "+382"),
    ("MZ", "Mozambique", "+258"),
    ("MM", "Myanmar", "+95"),
    ("NA", "Namibia", "+264"),
    ("NR", "Nauru", "+674"),
    ("NP", "Nepal", "+977"),
    ("NI", "Nicaragua", "+505"),
    ("NE", "Níger", "+227"),
    ("NG", "Nigeria", "+234"),
    ("NO", "Noruega", "+47"),
    ("NZ", "Nueva Zelanda", "+64"),
    ("OM", "Omán", "+968"),
    ("NL", "Países Bajos", "+31"),
    ("PK", "Pakistán", "+92"),
    ("PW", "Palaos", "+680"),
    ("PA", "Panamá", "+507"),
    ("PG", "Papúa Nueva Guinea", "+675"),
    ("PY", "Paraguay", "+595"),
    ("PE", "Perú", "+51"),
    ("PL", "Polonia", "+48"),
    ("PT", "Portugal", "+351"),
    ("GB", "Reino Unido", "+44"),
    ("CF", "República Centroafricana", "+236"),
    ("CG", "República del Congo", "+242"),
    ("CD", "República Democrática del Congo", "+243"),
    ("RW", "Ruanda", "+250"),
    ("RO", "Rumanía", "+40"),
    ("RU", "Rusia", "+7"),
    ("WS", "Samoa", "+685"),
    ("SN", "Senegal", "+221"),
    ("RS", "Serbia", "+381"),
    ("SC", "Seychelles", "+248"),
    ("SL", "Sierra Leona", "+232"),
    ("SG", "Singapur", "+65"),
    ("SY", "Siria", "+963"),
    ("SO", "Somalia", "+252"),
    ("LK", "Sri Lanka", "+94"),
    ("SZ", "Suazilandia", "+268"),
    ("ZA", "Sudáfrica", "+27"),
    ("SD", "Sudán", "+249"),
    ("SS", "Sudán del Sur", "+211"),
    ("SE", "Suecia", "+46"),
    ("CH", "Suiza", "+41"),
    ("SR", "Surinam", "+597"),
    ("TH", "Tailandia", "+66"),
    ("TW", "Taiwán", "+886"),
    ("TZ", "Tanzania", "+255"),
    ("TJ", "Tayikistán", "+992"),
    ("TL", "Timor Oriental", "+670"),
    ("TG", "Togo", "+228"),
    ("TO", "Tonga", "+676"),
    ("TT", "Trinidad y Tobago", "+1"),
    ("TN", "Túnez", "+216"),
    ("TM", "Turkmenistán", "+993"),
    ("TR", "Turquía", "+90"),
    ("UA", "Ucrania", "+380"),
    ("UG", "Uganda", "+256"),
    ("UY", "Uruguay", "+598"),
    ("UZ", "Uzbekistán", "+998"),
    ("VU", "Vanuatu", "+678"),
    ("VA", "Ciudad del Vaticano", "+379"),
    ("VE", "Venezuela", "+58"),
    ("VN", "Vietnam", "+84"),
    ("YE", "Yemen", "+967"),
    ("ZM", "Zambia", "+260"),
    ("ZW", "Zimbabue", "+263"),
]

COUNTRIES.sort(key=lambda c: c[1])

# Default selection for a Spain-first market.
DEFAULT_COUNTRY_ISO = "ES"

_CODES_BY_ISO = {iso: code for iso, _name, code in COUNTRIES}


def dial_code_for(iso: str) -> str | None:
    return _CODES_BY_ISO.get(iso)
